
name: Run Test
on: [push] # Or even on: workflow_dispatch for manual trigger

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run my local composite action
        uses: ./.github/actions/test 